#!/usr/bin/env python3

import os
import math
import argparse
import struct
import pathlib
import littlefs
from py_decl import PyDecl, UF2Reader


UF2_MAGIC_START0 = 0x0A324655  # "UF2\n"
UF2_MAGIC_START1 = 0x9E5D5157  # Randomly selected
UF2_MAGIC_END    = 0x0AB16F30  # Ditto
FS_START_ADDR    = 0x1012c000  # Pico W MicroPython LFSV2 offset
FS_SIZE          = 848 * 1024


FAMILY_ID_RP2040 = 0xe48bff56  # RP2040
FAMILY_ID_PAD    = 0xe48bff57  # ???
FAMILY_ID_RP2350 = 0xe48bff59  # RP2350

BLOCK_SIZE = 512
DATA_SIZE = 256
HEADER_SIZE = 32
FOOTER_SIZE = 4
PADDING_SIZE = BLOCK_SIZE - DATA_SIZE - HEADER_SIZE - FOOTER_SIZE
DATA_PADDING = b"\x00" * PADDING_SIZE


def uf2_to_bin(data, valid_family_ids=None):
    valid_family_ids = valid_family_ids or (FAMILY_ID_RP2040, FAMILY_ID_RP2350)

    for offset in range(0, len(data), BLOCK_SIZE):
        start0, start1, flags, addr, size, block_no, num_blocks, family_id = struct.unpack(b"<IIIIIIII", data[offset:offset + HEADER_SIZE])
        if args.debug:
            print(f"Block {block_no}/{num_blocks} addr {addr:08x} size {size}")
        block_data = data[offset + HEADER_SIZE:offset + HEADER_SIZE + DATA_SIZE]
        if family_id not in valid_family_ids:
            continue
        yield addr, family_id, num_blocks, block_data


def bin_to_uf2(sections):
    total_blocks = 0
    block_no = 0

    for section in sections:
        offset, data, family_id = section

        total_blocks = (len(data) + (DATA_SIZE - 1)) // DATA_SIZE

        if args.debug:
            print(f"uf2: Adding {len(data)} bytes at 0x{offset:08x}")

        num_blocks = (len(data) + (DATA_SIZE - 1)) // DATA_SIZE

        flags = 0x0
        flags |= 0x2000

        for index in range(num_blocks):
            ptr = DATA_SIZE * index

            chunk = data[ptr:ptr + DATA_SIZE].rjust(DATA_SIZE, b"\x00")

            header = struct.pack(
                b"<IIIIIIII",
                UF2_MAGIC_START0, UF2_MAGIC_START1, flags,
                ptr + offset, DATA_SIZE, block_no, total_blocks,
                family_id)

            footer = struct.pack(b"<I", UF2_MAGIC_END)

            block = header + chunk + DATA_PADDING + footer

            block_no += 1

            if len(block) != BLOCK_SIZE:
                raise RuntimeError("Invalid block size")

            yield block


parser = argparse.ArgumentParser()
parser.add_argument("--filename", type=pathlib.Path, default="filesystem", help="Output filename.")
parser.add_argument("--fs-start", type=int, default=None, help="Filesystem offset.")
parser.add_argument("--fs-size", type=int, default=None, help="Filesystem size.")
parser.add_argument("--fs-compact", action="store_true", help="Compact filesystem to used blocks.")
parser.add_argument("--block-size", type=int, default=4096, help="LFS block size in Kb.")
parser.add_argument("--read-size", type=int, default=256, help="LFS read size in Kb.")
parser.add_argument("--prog-size", type=int, default=32, help="LFS prog size in Kb.")
parser.add_argument("--manifest", default=None, help="Manifest to filter copied files.")
parser.add_argument("--append-to", type=pathlib.Path, default=None, help="uf2 file to append filesystem.")
parser.add_argument("--debug", action="store_true", help="Debug output.")
parser.add_argument("--verbose", action="store_true", help="Verbose output.")
parser.add_argument("source_dir", type=pathlib.Path, help="Source directory.")
args = parser.parse_args()

if args.fs_start is None or args.fs_size is None:
    if args.append_to is None:
        raise argparse.ArgumentError("Either an --append-to UF2 file or explicit --fs-start and --fs-size required!")

    if not args.append_to.is_file():
        raise RuntimeError(f"Could not find {args.append_to}")

    py_decl = PyDecl(UF2Reader(args.append_to))
    parsed = py_decl.parse()
    block_devices = parsed.get("BlockDevice", [])
    for block_device in block_devices:
        args.fs_start = block_device.get("address")
        args.fs_size = block_device.get("size")
        print(f"Auto detected fs: 0x{args.fs_start:08x} ({args.fs_start}), {args.fs_size} bytes.")
        break

block_count = math.ceil(args.fs_size / args.block_size)
if block_count * args.block_size != args.fs_size:
    print("image size should be a multiple of block size")
    exit(1)

lfs = littlefs.LittleFS(
    block_size=args.block_size,
    block_count=block_count,
    read_size=args.read_size,
    prog_size=args.prog_size,
)

output_filename = args.filename


def copy_files(lfs, todo, source_dir):
    for src in todo:
        if src.is_dir():
            dst = src.relative_to(source_dir)
            if args.verbose:
                print(f"- mkdir: {dst}")
            lfs.makedirs(dst.as_posix().replace("\\", "/"), exist_ok=True)
        if src.is_file():
            dst = src.relative_to(source_dir)
            if args.verbose:
                print(f"- copy: {src} to {dst}")
            with lfs.open(dst.as_posix().replace("\\", "/"), "wb") as outfile:
                with open(src, "rb") as infile:
                    outfile.write(infile.read())


def copy_manifest_or_dir(lfs, source_dir):
    if args.manifest is None:
        print(f"Copying directory: {source_dir}")
        # Walk the entire source dir and copy *everything*
        search_path = os.path.join("**", "*")
        copy_files(lfs, source_dir.glob(search_path), source_dir)

    else:
        print(f"Using manifest: {args.manifest}")
        # Copy files/globs listed in the manifest relative to the source dir
        todo = open(args.manifest, "r").read().split("\n")
        for item in todo:
            parent_dir = pathlib.Path(item).parent
            lfs.makedirs(str(parent_dir), exist_ok=True)
            copy_files(lfs, source_dir.glob(item), source_dir)


copy_manifest_or_dir(lfs, args.source_dir)

# Write a .bin with *just* the filesystem
bin_filename = output_filename.with_suffix(".bin")
lfs_used_bytes = len(lfs.context.buffer)

if args.fs_compact:
    lfs_used_bytes = lfs.used_block_count * args.block_size

    print(f"Compacting LittleFS to {lfs_used_bytes / 1024}K.")

    lfs_compact = littlefs.LittleFS(
        block_size=args.block_size,
        block_count=lfs.used_block_count,
        read_size=args.read_size,
        prog_size=args.prog_size,
    )

    copy_manifest_or_dir(lfs_compact, args.source_dir)

    lfs_compact.fs_grow(block_count)

    lfs_data = lfs_compact.context.buffer

else:
    lfs_data = lfs.context.buffer


with open(bin_filename, "wb") as f:
    f.write(lfs_data)

print(f"Written: {bin_filename}")


# Write a .uf2 with *just* the filesystem
uf2_filename = output_filename.with_suffix(".uf2")

with open(uf2_filename, "wb") as f:
    for block in bin_to_uf2([(args.fs_start, lfs_data, FAMILY_ID_RP2040)]):
        f.write(block)

print(f"Written: {uf2_filename}")


if args.append_to is not None:
    if not args.append_to.is_file():
        raise RuntimeError(f"Could not find {args.append_to}")

    uf2_append_filename = output_filename.with_name(f"{args.append_to.stem}-{uf2_filename.stem}.uf2")

    print(f"Appending to {args.append_to}")

    with open(uf2_append_filename, "wb") as f:
        append_to = open(args.append_to, "rb").read()

        # HACK: Write the weird two block section from the front of RP2350 UF2s
        try:
            _, _, num_blocks, _ = next(uf2_to_bin(append_to, valid_family_ids=(FAMILY_ID_PAD, )))
            f.write(append_to[0: num_blocks * BLOCK_SIZE])
        except StopIteration:
            pass

        # Read the first block address, this will be the base offset
        start_addr, family_id, num_blocks, _ = next(uf2_to_bin(append_to))

        # Read the .uf2 contents to binary
        data = b"".join(map(lambda b: b[3], uf2_to_bin(append_to)))

        # Figure out how much padding we need
        fw_size = args.fs_start - start_addr

        # Pad the supplied firmware up to our filesystem range
        # We *could* create a .uf2 without this padding, supplying the
        # firmware & filesystem blocks with different range offsets.
        # However while this works fine in Picotool - which detects
        # and writes each sequential range of data - it completely
        # fails to write the second set (filesystem) in the RP2040
        # bootloader.
        # So, humph, we'll just pad and concat the two which makes
        # for a bigger, but actually compatible .uf2.
        data = data.ljust(fw_size, b"\xff")

        # Add our filesystem onto the data
        data += lfs_data

        # Pack data into a uf2 at offset start_addr
        # This will be FS_START_ADDR if we're not appending.
        for block in bin_to_uf2([(start_addr, data, family_id)]):
            f.write(block)

        print(f"Written: {uf2_append_filename}")
